import type { SupplyEvent } from "./types";

export const dummyDataSource : SupplyEvent[] = [
  {
    key: "0",
    locationType: "Terminal",
    applicability: "Flint Buckeye",
    product: "All",
    startDate: "3/5/2023",
    endDate: "3/8/2023",
    duration: "3",
    impact: "Medium",
    category: "Weather",
    comment: "Winter storm, extremly low demand",
  },
  {
    key: "1",
    locationType: "Terminal",
    applicability: "Carteret KMI",
    product: "Diesel",
    startDate: "3/5/2023",
    endDate: "3/14/2023",
    duration: "9",
    impact: "Medium",
    category: "Terminal Disruption",
    comment: "Terminal Down, customer shifted to KMI",
  },
  {
    key: "2",
    locationType: "Region",
    applicability: "Flint Buckeye",
    product: "Diesel",
    startDate: "3/21/2023",
    endDate: "4/10/2023",
    duration: "20",
    impact: "High",
    category: "Arb",
    comment: "NYH/Chi Arb open for full month, Oh demand shifted",
  },
  {
    key: "3",
    locationType: "Terminal",
    applicability: "Flint Buckeye",
    product: "Diesel",
    startDate: "3/15/2023",
    endDate: "Ongoing",
    duration: "25",
    impact: "High",
    category: "Arb",
    comment: "NYH/Chi Arb open for full month, Oh demand shifted",
  },
];
